language: python
python:
  - "2.7"
environment:
    DJANGO_SETTINGS_MODULE: photogenic.settings.test  
services:
  - postgresql
before_install:
  - "pip install -r requirements.txt"
install:
  - "pip install coveralls" 
script:
  - export SECRET_KEY=$SECRET_KEY
  - python manage.py test --noinput --settings=photogenic.settings
after_success:
  - coveralls
branches:
  only:
  - develop
