language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
    - TRAVIS_BUILD=true
    - DB=postgres

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - coverage run manage.py test photogenic/main--noinput --settings=photogenic.settings.test
  
branches:
  only:
  - develop
after_success:
  - coveralls