language: python
python:
  - "2.7"
branches:
  only:
  - develop
services:
  - postgresql
before_install:
  - "pip install -r requirements.txt"
install:
  - "pip install coveralls" 
env:
  - SECRET_KEY='&gj3fvzp2p@lh2eo^1w618g4nd!3ztlhg8jl)^z+qr4iv+zdez'  
script:
  - python manage.py test --noinput --settings=photogenic.settings.test
after_success:
  - coveralls
