language: python
python:
  - "2.7"
environment:
    DJANGO_SETTINGS_MODULE: photogenic.base.test  
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
    - TRAVIS_BUILD=true
    - DB=postgres

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
   - coverage run photogenic/manage.py test photogenic/main/ --noinput --settings=bucketlist.settings
branches:
  only:
  - develop
after_success:
  - coveralls