language: python
python:
  - "2.7"
services:
  - postgresql
before_install:
  - "pip install -r requirements.txt"
install:
  - "pip install coveralls"
script:
  - python manage.py test --noinput
after_success:
  - coveralls
branches:
  only:
  - develop
